baseURL = 'http://docs.devboer.com/'
languageCode = 'en-us'
title = 'dev Boer Docs'
theme = 'PaperMod'
params:
  homeInfoParams:
    Title: Hi there wave
    Content: Noting my adventures running a home server
